language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - rabbitmq

before_install:
  - sudo ./travis-install-deps.sh
  - sudo ./travis-config-deps.sh
  - sudo freshclam
  - sudo service clamav-daemon start

before_script:
  - sudo ./tools/prepareRMQ.sh

script:
  - sudo netstat -an46
  - ./gradlew configureEnvironment
  - ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)

