language: java
sudo: required

jdk:
  - oraclejdk8

services:
  - docker

before_install:
#  - sudo ./travis-install-deps.sh
#  - sudo ./travis-config-deps.sh
#  - sudo freshclam
#  - sudo service clamav-daemon start
#  - sudo service activemq restart
#  - sudo apt-get install postgresql-client
#  - sudo systemctl stop postgresql
  - sudo netstat -lnp46
  - sudo /etc/init.d/postgresql stop
  - sudo netstat -lnp46
  - env
  - cd docker
  - docker-compose up -d
  - cd $TRAVIS_BUILD_DIR

before_script:
#  - sudo ./tools/prepareRMQ.sh
#  - sudo ./tools/preparePostgreSQL.sh

script:
  - sudo netstat -lnp46
  - ./gradlew configureEnvironment
  - ./gradlew check -s -i

after_success:
  - bash <(curl -s https://codecov.io/bash)

