server.name: kibana
server.host: "0"
elasticsearch.url: http://localhost:9200
elasticsearch.username: elastic
elasticsearch.password: changeme

xpack.security.enabled: false
xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.reporting.enabled: false
