@startuml

title Remote REST interface

interface "HTTP" as http
interface "message broker" as broker
interface "message broker\n(file replication)" as broker2


package "REST" {
    [REST 3]
    [REST 2]
    [REST 1]
}

package "core node 1" {
    [core 1]
    [AV service 1]
    [file service 1]
}

package "core node 2" {
    [core 2]
    [AV service 2]
    [file service 2]
}

package "core node 3" {
    [core 3]
    [AV service 3]
    [file service 3]
}

package "replication service 1" {
    [file service 4]
    [database 4]
}

package "replication service 2" {
    [file service 5]
    [database 5]
}

http -- [REST 1]
http -- [REST 2]
http -- [REST 3]

[REST 1] -- broker
[REST 2] -- broker
[REST 3] -- broker

broker -- [core 1]
broker -- [core 2]
broker -- [core 3]

[core 1] -- [AV service 1]
[core 2] -- [AV service 2]
[core 3] -- [AV service 3]

[core 1] -- [file service 1]
[core 2] -- [file service 2]
[core 3] -- [file service 3]

[AV service 1] -- [ClamAV 1]
[AV service 2] -- [ClamAV 2]
[AV service 3] -- [ClamAV 3]

[file service 1] -- [database 1]
[file service 2] -- [database 2]
[file service 3] -- [database 3]

[file service 1] -- broker2
[file service 2] -- broker2
[file service 3] -- broker2
[file service 4] -up- broker2
[file service 5] -up- broker2

[file service 4] -left- [database 4]
[file service 5] - [database 5]

@enduml
