@startuml

title Remote REST interface detail

interface "HTTP" as http
interface "message broker" as broker

package "MessageProcessor" {
    [CompositeMessageProcessor]
    [AvCheckMessageProcessor]
    [FileMessageProcessor]
}

http -- [MainController]
http -- [CheckController]
http -- [FileController]

[MainController] -- [RestService]
[CheckController] -- [RestService]
[FileController] -- [RestService]

[RestService] -- [AvServiceClient]
[RestService] -- [FileServiceClient]
[RestService] -- [ResponseClient]

[AvServiceClient] -- [AvNetworkComponent]
[AvServiceClient] - [ResponseClient]

[FileServiceClient] -- [AvNetworkComponent]
[ResponseClient] -- [AvNetworkComponent]

[AvNetworkComponent] -- broker

[AvNetworkComponent 2] -up- broker

[AvServer] -up- [AvNetworkComponent 2]
[AvServer] -- [CompositeMessageProcessor]

[CompositeMessageProcessor] - [AvCheckMessageProcessor]
[CompositeMessageProcessor] -left- [FileMessageProcessor]

[FileMessageProcessor] -- [FileService]
[AvCheckMessageProcessor] -- [AvService]

[AvService] -- [AvProgram]

@enduml
